name = "remix-cloudflare-workers"
type = "javascript"

account_id = ""
route = ""
workers_dev = true
zone_id = ""

kv-namespaces = [
  {binding = "DATAENTRY", preview_id = "ee152cb4ebc347ba9099d09a823723b1", id = "d7b843eb4107425abcf7fd1918bcd3bb"},
]

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
